---
- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Install packages
  action: yum name={{item}} state=latest update_cache=yes
  with_items:
  - pkgconfig
  - git
  - vim
  - curl
  - wget
  - tree
